Write-Host "/****************************************/"
Write-Host "/* MERAKI DEVICES INDEX LAMBDA FUNCTION */"
Write-Host "/****************************************/"
Write-Host ""
Write-Host "Compressing Files"
Write-Host "-----------------"
Compress-Archive -LiteralPath ./conapps-merakiQuotes-index.js, ../modules/auth.module.js, ./node_modules, ../models/merakiQuotes.model.js -DestinationPath ./merakiQuotesIndex.zip -CompressionLevel Optimal -Force
Write-Host ""
Write-Host "Done!"
Write-Host ""
Write-Host "Uploading Zip to AWS"
Write-Host "--------------------"
Write-Host ""
aws lambda update-function-code --function-name conapps-merakiQuotes-index --zip-file fileb://merakiQuotesIndex.zip
Write-Host ""
Write-Host "Done!"
Write-Host ""