// SIGNUP ACTIONS
export const DOING_SIGNUP_USER   = 'DOING_SIGNUP_USER'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_ERROR   = 'SIGNUP_USER_ERROR'
// LOGIN ACTIONS
export const DOING_LOGIN_USER   = 'DOING_LOGIN_USER,'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS,'
export const LOGIN_USER_ERROR   = 'LOGIN_USER_ERROR'
// MERAKI DEVICES ACTIONS
export const DOING_GET_MERAKI_DEVICES   = 'DOING_GET_MERAKI_DEVICES'
export const GET_MERAKI_DEVICES_SUCCESS = 'GET_MERAKI_DEVICES_SUCCESS'
export const GET_MERAKI_DEVICES_ERROR   = 'GET_MERAKI_DEVICES_ERROR'
// USERS ACTIONS
export const DOING_USERS_INDEX   = 'DOING_USERS_INDEX'
export const USERS_INDEX_SUCCESS = 'USERS_INDEX_SUCCESS'
export const USERS_INDEX_ERROR   = 'USERS_INDEX_ERROR'